# Generated by Django 3.0.8 on 2021-06-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200722_0405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='phone',
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.CharField(max_length=50),
        ),
    ]
