# Generated by Django 3.0.8 on 2021-06-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210630_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='phone',
            field=models.CharField(default='0000000', max_length=12),
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone',
            field=models.CharField(default='0000000', max_length=12),
        ),
    ]
